// Package schema holds the JSON Schemas of hwspec's documents, generated by
// tools/genschema from their Go types: the capture format (ADR 0003, from
// internal/report) and the advice document (ADR 0009, from
// internal/advisor). A new version adds a <format>-vN.json; older files are
// frozen.
package schema

import _ "embed" // for JSON and AdviceJSON

//go:generate go run ../tools/genschema -dir .

// URL is the capture schema's $id, and what captures name in their
// "$schema" key so editors can validate them. It's on main because a v1
// file only ever grows.
const URL = "https://raw.githubusercontent.com/jiegui2025/hwspec/main/schema/capture-v1.json"

// JSON is the capture schema for the current schema_version.
//
//go:embed capture-v1.json
var JSON []byte

// AdviceURL is the advice schema's $id, which `hwspec advise -f json`
// names in its "$schema" key.
const AdviceURL = "https://raw.githubusercontent.com/jiegui2025/hwspec/main/schema/advice-v1.json"

// AdviceJSON is the advice schema for the current advice_version.
//
//go:embed advice-v1.json
var AdviceJSON []byte
